spring.application.name=Language App

spring.datasource.url=jdbc:postgresql://localhost:5432/languageapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql = true
spring.jpa.open-in-view=false
# Needed for multiple embeddable objects of the same type in one table:
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
# Use data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jackson.deserialization.fail-on-unknown-properties = true

logging.level.sql=trace

# TODO: This makes using LAZY loading easier, but the problems should be handled in another way.
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

org.atmatto.languageapp.jwtSecret=${JWT_SECRET}
# TODO: Test session expiration handling on front end.
org.atmatto.languageapp.jwtExpirationMinutes=60
logging.level.org.springframework.security=trace
